#! /bin/bash

if [ ${#1} -eq 0 ]
then
	echo "No commit, pleases try again with commit description" 1>&2
	exit 1
fi

git add .

echo -e "\033[34mFiles Modifications :"

git status --porcelain

echo -e "Your commit : $1"
echo -e ""
echo -e "------------------\033[0m\n"
git commit -m "$1"

git push
