#! /bin/bash

if test -z "$1"
	then echo "usage : ./script \"processus name\""
	exit  
fi
echo "\033[31m\n/////MEMORY CHECKER/////\n\033[0m"
echo "\033[31mYour Processus : "
echo $1
echo  "\033[0m"
echo "\033[96mNAME             MEMORY\n\033[32m"

top -stats command,mem | grep $1


